events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # Port et nom de domaine
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name dylekici.42.fr;

        # Protocoles de sécurité stricts exigés par le sujet
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Dossier racine où se trouvera le site
        root /var/www/html;
        index index.php index.html index.htm;

        # Redirection standard de WordPress (Modifié ici)
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Comment traiter les fichiers PHP (en les envoyant à WordPress)
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            
            # --- LES PARAMÈTRES ANTI-BOUCLE DE REDIRECTION ---
            fastcgi_param HTTPS on;
            fastcgi_param SERVER_PORT 443;
            fastcgi_param HTTP_X_FORWARDED_PROTO https;
        }
    }
}